### PR TITLE
fix: fix target nodes blank when language is source language #9

### PR DESCRIPTION
**Pull request by gergely-gyorgy-both**

### CODE REVIEW

**Comment by gergely-gyorgy-both** [comment]
Fixing issue https://github.com/daniel-sc/xliff-simple-merge/issues/9

P.S. This is my first-ever pull request, please tell me if I messed anything up ;)

**Review by daniel-sc — APPROVED** [review]
This looks good! Extra kudos if you provide a unit test covering the issue :)

**Comment by gergely-gyorgy-both** [comment]
Thanks, will do it tomorrow!

**Comment by daniel-sc** [comment]
@gergely-gyorgy-both Thanks very much. I'll do a release tomorrow!

**Pull request merged**
